### ISSUE TITLE
Create SLI/SLO to monitor the use of each Kebechet Manager

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#546]
**Is your feature request related to a problem? Please describe.**
As Thoth Manager,

I want to have SLI about the use of Kebechet managers to monitor and prioritize next features.

**Describe the solution you'd like**
Check how many PR are opened and merged by managers

**Describe alternatives you've considered**

**Additional context**
- Thoth SLI/SLO
- Reuse mi project:  https://github.com/thoth-station/mi

**Comment by goern** [comment]
@xtuchyna @pacospace what is the status of this?

**Comment by xtuchyna** [comment]
> @xtuchyna @pacospace what is the status of this?

I am currently working on a dashboard visualization for today's demo and the last thing that remains is just to schedule workflows for all repos that use kebechet managers.

**Comment by pacospace** [comment]
-> https://github.com/orgs/thoth-station/projects/13#card-50305419

**Comment by pacospace** [comment]
@xtuchyna what is the status?

**Comment by xtuchyna** [comment]
Requirements as for know:

- [ ] Check mi-scheduler new version released ( https://github.com/thoth-station/mi-scheduler/issues/72 )
- [ ] Check that creating job from mi-scheduler cronjob works and gathers knowledge
- [ ] Fix CronJob not scheduling hourly (and maybe change that for daily)
- [ ] Store metrics out of gathered knowledge on Ceph

**Comment by goern** [comment]
and... could we resemble something like the github punchcard for all the contributions kebechet is going? coming back to the question: "how much work is the bot saving the humans?"

**Comment by pacospace** [comment]
> Requirements as for know:
> 
> * [x]  Check mi-scheduler new version released ( [thoth-station/mi-scheduler#72](https://github.com/thoth-station/mi-scheduler/issues/72) )
> * [ ]  Check that creating job from mi-scheduler cronjob works and gathers knowledge
> * [ ]  Fix CronJob not scheduling hourly (and maybe change that for daily)
> * [ ]  Store metrics out of gathered knowledge on Ceph

pre-requisiites:

- [x] Check mi-scheduler new version released ( https://github.com/thoth-station/mi-scheduler/issues/72 )
- [ ] Check that creating job from mi-scheduler cronjob works and gathers knowledge
- [ ] Fix CronJob not scheduling hourly (and maybe change that for daily)

Steps: 
- [ ] Store metrics out of gathered knowledge on Ceph (https://github.com/thoth-station/mi/issues/331)

**Comment by goern** [comment]
What is the status on this? @xtuchyna are you actively working on it?

/remove-lifecycle stale

**Comment by xtuchyna** [comment]
@goern this should be done, I am gonna test the data aggregation and let you know

**Comment by goern** [comment]
hey fellas, what is the state of this? demoable?

**Comment by goern** [comment]
ping?!

**Comment by goern** [comment]
@xtuchyna @Gkrumbach07 could you have a look at this, and give it a little love. plan it and relate it to one of our key results? thx!
