### ISSUE TITLE
Actively send Kebechet services (Internal Trigger)

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#571]
**Is your feature request related to a problem? Please describe.**
As Thoth Manager,

I want Kebechet to actively provide services to users that has Kebechet enabled depending on the managers activated in `.thoth.yaml`.

As Kebechet User,

I want to receive Kebechet services based on the manager I enabled in `.thoth.yaml` file, even when something changed in it.

**Describe the solution you'd like**
Currently we receives Kafka message about new packages solved or when a release is going missing. Thoth should actively act on that and provide advise on any change in user software stack.

Pre-requisites:

`thoth-storages`
- [x] https://github.com/thoth-station/storages/issues/2016

- [x] Extend Kebechet_github_installation table to have software stack ID: https://github.com/thoth-station/storages/issues/2038

- [x] Kebechet can run using repo url and service name: https://github.com/thoth-station/common/issues/1009

Tasks required:

- [x] Create Kebehcet Administrator https://github.com/thoth-station/workflow-helpers/issues/148

The rest rest is already handled by the investigator with existing logic.

**Describe alternatives you've considered**

**Additional context**
